apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231101101515.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231101101515.0.0+build.02e9424
  releaseNotes: |
    Release v20231101101515.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-11-2023-04-20-39-592384360/where-for-dinner-search-my-apps-bundle@sha256:78ca04867baf32407727a2265b46f0dc4e96c5c67a5e25db00b4c19bf92479bd
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

