apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231101101434.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231101101434.0.0+build.02e9424
  releaseNotes: |
    Release v20231101101434.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-11-2023-04-20-39-592384360/where-for-dinner-my-apps-bundle@sha256:402099e0de904648f4ecf95609c2a0accf52d38afe43e4988ddec9b9afc1ea1c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

