apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20231101101511.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20231101101511.0.0+build.02e9424
  releaseNotes: |
    Release v20231101101511.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-01-11-2023-04-20-39-592384360/where-for-dinner-availability-my-apps-bundle@sha256:3f893ba4be5ef5e0ce3145b1b02f680d869f8a6e5f5daae2d7711afede3ce0b5
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

